[
  {
     "Position": "CF",
     "Player Name": "C. RONALDO",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "PORTUGAL",
     "Height": 185,
     "Weight": 80,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 94
  },
  {
     "Position": "SS",
     "Player Name": "L. MESSI",
     "Team Name": "BARCELONA",
     "Nationality": "ARGENTINA",
     "Height": 170,
     "Weight": 72,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 94
  },
  {
     "Position": "LWF",
     "Player Name": "NEYMAR",
     "Team Name": "PSG",
     "Nationality": "BRAZIL",
     "Height": 175,
     "Weight": 68,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 93
  },
  {
     "Position": "GK",
     "Player Name": "DAVID DE GEA",
     "Team Name": "MAN RED",
     "Nationality": "SPAIN",
     "Height": 192,
     "Weight": 76,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 91
  },
  {
     "Position": "GK",
     "Player Name": "M. NEUER",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 193,
     "Weight": 92,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "CF",
     "Player Name": "L. SU�REZ",
     "Team Name": "BARCELONA",
     "Nationality": "URUGUAY",
     "Height": 182,
     "Weight": 86,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "CMF",
     "Player Name": "T. KROOS",
     "Team Name": "MD WHITE",
     "Nationality": "GERMANY",
     "Height": 182,
     "Weight": 78,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "LWF",
     "Player Name": "E. HAZARD",
     "Team Name": "LONDON FC",
     "Nationality": "BELGIUM",
     "Height": 173,
     "Weight": 76,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "CF",
     "Player Name": "R. LEWANDOWSKI",
     "Team Name": "Free Agents",
     "Nationality": "POLAND",
     "Height": 185,
     "Weight": 79,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "CF",
     "Player Name": "A. GRIEZMANN",
     "Team Name": "KB RED WHITE",
     "Nationality": "FRANCE",
     "Height": 174,
     "Weight": 72,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "AMF",
     "Player Name": "K. DE BRUYNE",
     "Team Name": "MAN BLUE",
     "Nationality": "BELGIUM",
     "Height": 181,
     "Weight": 68,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "RWF",
     "Player Name": "M. SALAH",
     "Team Name": "LIVERPOOL",
     "Nationality": "EGYPT",
     "Height": 175,
     "Weight": 71,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 90
  },
  {
     "Position": "CB",
     "Player Name": "SERGIO RAMOS",
     "Team Name": "MD WHITE",
     "Nationality": "SPAIN",
     "Height": 183,
     "Weight": 75,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 89
  },
  {
     "Position": "CMF",
     "Player Name": "L. MODRI?",
     "Team Name": "MD WHITE",
     "Nationality": "CROATIA",
     "Height": 174,
     "Weight": 65,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 89
  },
  {
     "Position": "CF",
     "Player Name": "E. CAVANI",
     "Team Name": "PSG",
     "Nationality": "URUGUAY",
     "Height": 184,
     "Weight": 71,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 89
  },
  {
     "Position": "CB",
     "Player Name": "M. HUMMELS",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 191,
     "Weight": 92,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 89
  },
  {
     "Position": "GK",
     "Player Name": "J. OBLAK",
     "Team Name": "KB RED WHITE",
     "Nationality": "SLOVENIA",
     "Height": 188,
     "Weight": 77,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 89
  },
  {
     "Position": "CF",
     "Player Name": "H. KANE",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "ENGLAND",
     "Height": 188,
     "Weight": 76,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 89
  },
  {
     "Position": "CB",
     "Player Name": "PIQU�",
     "Team Name": "BARCELONA",
     "Nationality": "SPAIN",
     "Height": 194,
     "Weight": 85,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "CF",
     "Player Name": "G. HIGUA�N",
     "Team Name": "MILAN",
     "Nationality": "ARGENTINA",
     "Height": 184,
     "Weight": 82,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "CF",
     "Player Name": "S. AG�ERO",
     "Team Name": "MAN BLUE",
     "Nationality": "ARGENTINA",
     "Height": 173,
     "Weight": 70,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "LB",
     "Player Name": "MARCELO",
     "Team Name": "MD WHITE",
     "Nationality": "BRAZIL",
     "Height": 174,
     "Weight": 75,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "RWF",
     "Player Name": "G. BALE",
     "Team Name": "MD WHITE",
     "Nationality": "WALES",
     "Height": 183,
     "Weight": 74,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "CF",
     "Player Name": "P. AUBAMEYANG",
     "Team Name": "ARSENAL",
     "Nationality": "GABON",
     "Height": 187,
     "Weight": 80,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "LWF",
     "Player Name": "P. COUTINHO",
     "Team Name": "BARCELONA",
     "Nationality": "BRAZIL",
     "Height": 171,
     "Weight": 71,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "SS",
     "Player Name": "P. DYBALA",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "ARGENTINA",
     "Height": 177,
     "Weight": 74,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "GK",
     "Player Name": "M. TER STEGEN",
     "Team Name": "BARCELONA",
     "Nationality": "GERMANY",
     "Height": 187,
     "Weight": 85,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 88
  },
  {
     "Position": "CMF",
     "Player Name": "INIESTA",
     "Team Name": "Free Agents",
     "Nationality": "SPAIN",
     "Height": 171,
     "Weight": 68,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "GK",
     "Player Name": "H. LLORIS",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "FRANCE",
     "Height": 188,
     "Weight": 78,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CB",
     "Player Name": "G. CHIELLINI",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "ITALY",
     "Height": 187,
     "Weight": 84,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CF",
     "Player Name": "K. BENZEMA",
     "Team Name": "MD WHITE",
     "Nationality": "FRANCE",
     "Height": 185,
     "Weight": 79,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "AMF",
     "Player Name": "DAVID SILVA",
     "Team Name": "MAN BLUE",
     "Nationality": "SPAIN",
     "Height": 173,
     "Weight": 67,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CB",
     "Player Name": "D. GOD�N",
     "Team Name": "KB RED WHITE",
     "Nationality": "URUGUAY",
     "Height": 186,
     "Weight": 78,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CMF",
     "Player Name": "A. VIDAL",
     "Team Name": "BARCELONA",
     "Nationality": "CHILE",
     "Height": 180,
     "Weight": 75,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "LWF",
     "Player Name": "A. S�NCHEZ",
     "Team Name": "MAN RED",
     "Nationality": "CHILE",
     "Height": 169,
     "Weight": 62,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CF",
     "Player Name": "DIEGO COSTA",
     "Team Name": "KB RED WHITE",
     "Nationality": "SPAIN",
     "Height": 188,
     "Weight": 85,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "AMF",
     "Player Name": "M. �ZIL",
     "Team Name": "ARSENAL",
     "Nationality": "GERMANY",
     "Height": 180,
     "Weight": 76,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "DMF",
     "Player Name": "SERGIO BUSQUETS",
     "Team Name": "BARCELONA",
     "Nationality": "SPAIN",
     "Height": 189,
     "Weight": 76,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CB",
     "Player Name": "THIAGO SILVA",
     "Team Name": "PSG",
     "Nationality": "BRAZIL",
     "Height": 183,
     "Weight": 79,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CF",
     "Player Name": "R. LUKAKU",
     "Team Name": "MAN RED",
     "Nationality": "BELGIUM",
     "Height": 190,
     "Weight": 94,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CB",
     "Player Name": "J. BOATENG",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 192,
     "Weight": 90,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "LWF",
     "Player Name": "DOUGLAS COSTA",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "BRAZIL",
     "Height": 170,
     "Weight": 65,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "AMF",
     "Player Name": "C. ERIKSEN",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "DENMARK",
     "Height": 175,
     "Weight": 71,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CMF",
     "Player Name": "THIAGO A.",
     "Team Name": "Free Agents",
     "Nationality": "SPAIN",
     "Height": 174,
     "Weight": 70,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "AMF",
     "Player Name": "J. RODR�GUEZ",
     "Team Name": "Free Agents",
     "Nationality": "COLOMBIA",
     "Height": 180,
     "Weight": 75,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "DMF",
     "Player Name": "CASEMIRO",
     "Team Name": "MD WHITE",
     "Nationality": "BRAZIL",
     "Height": 184,
     "Weight": 80,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CB",
     "Player Name": "V. VAN DIJK",
     "Team Name": "LIVERPOOL",
     "Nationality": "NETHERLANDS",
     "Height": 193,
     "Weight": 92,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CB",
     "Player Name": "S. UMTITI",
     "Team Name": "BARCELONA",
     "Nationality": "FRANCE",
     "Height": 182,
     "Weight": 75,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "LWF",
     "Player Name": "M. REUS",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 180,
     "Weight": 71,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CF",
     "Player Name": "M. ICARDI",
     "Team Name": "INTERNAZIONALE",
     "Nationality": "ARGENTINA",
     "Height": 181,
     "Weight": 75,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "GK",
     "Player Name": "EDERSON",
     "Team Name": "MAN BLUE",
     "Nationality": "BRAZIL",
     "Height": 188,
     "Weight": 86,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "GK",
     "Player Name": "ALISSON",
     "Team Name": "LIVERPOOL",
     "Nationality": "BRAZIL",
     "Height": 191,
     "Weight": 91,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "CMF",
     "Player Name": "N. KANT�",
     "Team Name": "LONDON FC",
     "Nationality": "FRANCE",
     "Height": 168,
     "Weight": 68,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 87
  },
  {
     "Position": "GK",
     "Player Name": "G. BUFFON",
     "Team Name": "PSG",
     "Nationality": "ITALY",
     "Height": 191,
     "Weight": 94,
     "Age": 40,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "GK",
     "Player Name": "S. HANDANOVI?",
     "Team Name": "INTERNAZIONALE",
     "Nationality": "SLOVENIA",
     "Height": 193,
     "Weight": 89,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CB",
     "Player Name": "L. BONUCCI",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "ITALY",
     "Height": 190,
     "Weight": 85,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CB",
     "Player Name": "M. BENATIA",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "MOROCCO",
     "Height": 188,
     "Weight": 88,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CMF",
     "Player Name": "M. HAM��K",
     "Team Name": "NAPOLI",
     "Nationality": "SLOVAKIA",
     "Height": 183,
     "Weight": 79,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CMF",
     "Player Name": "I. RAKITI?",
     "Team Name": "BARCELONA",
     "Nationality": "CROATIA",
     "Height": 184,
     "Weight": 78,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "RWF",
     "Player Name": "�. DI MAR�A",
     "Team Name": "PSG",
     "Nationality": "ARGENTINA",
     "Height": 180,
     "Weight": 75,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "DMF",
     "Player Name": "M. PJANI?",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "BOSNIA AND HERZEGOVINA",
     "Height": 180,
     "Weight": 72,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CF",
     "Player Name": "E. D�EKO",
     "Team Name": "ROMA",
     "Nationality": "BOSNIA AND HERZEGOVINA",
     "Height": 193,
     "Weight": 84,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "GK",
     "Player Name": "K. NAVAS",
     "Team Name": "MD WHITE",
     "Nationality": "COSTA RICA",
     "Height": 185,
     "Weight": 78,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CF",
     "Player Name": "D. MERTENS",
     "Team Name": "NAPOLI",
     "Nationality": "BELGIUM",
     "Height": 169,
     "Weight": 61,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "SS",
     "Player Name": "T. M�LLER",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 186,
     "Weight": 75,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CB",
     "Player Name": "N. OTAMENDI",
     "Team Name": "MAN BLUE",
     "Nationality": "ARGENTINA",
     "Height": 183,
     "Weight": 81,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CF",
     "Player Name": "C. IMMOBILE",
     "Team Name": "LAZIO",
     "Nationality": "ITALY",
     "Height": 184,
     "Weight": 80,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CMF",
     "Player Name": "KOKE",
     "Team Name": "KB RED WHITE",
     "Nationality": "SPAIN",
     "Height": 178,
     "Weight": 73,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "LB",
     "Player Name": "D. ALABA",
     "Team Name": "Free Agents",
     "Nationality": "AUSTRIA",
     "Height": 180,
     "Weight": 76,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "AMF",
     "Player Name": "ISCO",
     "Team Name": "MD WHITE",
     "Nationality": "SPAIN",
     "Height": 176,
     "Weight": 74,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CB",
     "Player Name": "R. VARANE",
     "Team Name": "MD WHITE",
     "Nationality": "FRANCE",
     "Height": 191,
     "Weight": 78,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "LB",
     "Player Name": "ALEX SANDRO",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "BRAZIL",
     "Height": 181,
     "Weight": 76,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CMF",
     "Player Name": "P. POGBA",
     "Team Name": "MAN RED",
     "Nationality": "FRANCE",
     "Height": 191,
     "Weight": 84,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "LWF",
     "Player Name": "S. MAN�",
     "Team Name": "LIVERPOOL",
     "Nationality": "SENEGAL",
     "Height": 175,
     "Weight": 69,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "AMF",
     "Player Name": "N. FEKIR",
     "Team Name": "OLYMPIQUE LYONNAIS",
     "Nationality": "FRANCE",
     "Height": 173,
     "Weight": 72,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CMF",
     "Player Name": "SA�L",
     "Team Name": "KB RED WHITE",
     "Nationality": "SPAIN",
     "Height": 181,
     "Weight": 70,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CF",
     "Player Name": "ROBERTO FIRMINO",
     "Team Name": "LIVERPOOL",
     "Nationality": "BRAZIL",
     "Height": 181,
     "Weight": 76,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "RB",
     "Player Name": "J. KIMMICH",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 176,
     "Weight": 73,
     "Age": 23,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "RWF",
     "Player Name": "K. MBAPP�",
     "Team Name": "PSG",
     "Nationality": "FRANCE",
     "Height": 178,
     "Weight": 73,
     "Age": 20,
     "Condition": "C",
     "Overall Rating": 86
  },
  {
     "Position": "CB",
     "Player Name": "V. KOMPANY",
     "Team Name": "MAN BLUE",
     "Nationality": "BELGIUM",
     "Height": 193,
     "Weight": 85,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CMF",
     "Player Name": "F�BREGAS",
     "Team Name": "LONDON FC",
     "Nationality": "SPAIN",
     "Height": 180,
     "Weight": 77,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "LB",
     "Player Name": "FILIPE LUIS",
     "Team Name": "KB RED WHITE",
     "Nationality": "BRAZIL",
     "Height": 183,
     "Weight": 73,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CMF",
     "Player Name": "FERNANDINHO",
     "Team Name": "MAN BLUE",
     "Nationality": "BRAZIL",
     "Height": 179,
     "Weight": 67,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CB",
     "Player Name": "MIRANDA",
     "Team Name": "INTERNAZIONALE",
     "Nationality": "BRAZIL",
     "Height": 186,
     "Weight": 78,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CB",
     "Player Name": "AZPILICUETA",
     "Team Name": "LONDON FC",
     "Nationality": "SPAIN",
     "Height": 178,
     "Weight": 78,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "RWF",
     "Player Name": "WILLIAN",
     "Team Name": "LONDON FC",
     "Nationality": "BRAZIL",
     "Height": 175,
     "Weight": 77,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CB",
     "Player Name": "T. ALDERWEIRELD",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "BELGIUM",
     "Height": 186,
     "Weight": 81,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "RMF",
     "Player Name": "H. MKHITARYAN",
     "Team Name": "ARSENAL",
     "Nationality": "ARMENIA",
     "Height": 177,
     "Weight": 75,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CB",
     "Player Name": "K. MANOLAS",
     "Team Name": "ROMA",
     "Nationality": "GREECE",
     "Height": 189,
     "Weight": 83,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "DMF",
     "Player Name": "N. MATI?",
     "Team Name": "MAN RED",
     "Nationality": "SERBIA",
     "Height": 194,
     "Weight": 85,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "LB",
     "Player Name": "JORDI ALBA",
     "Team Name": "BARCELONA",
     "Nationality": "SPAIN",
     "Height": 170,
     "Weight": 68,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CF",
     "Player Name": "A. LACAZETTE",
     "Team Name": "ARSENAL",
     "Nationality": "FRANCE",
     "Height": 175,
     "Weight": 73,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "GK",
     "Player Name": "W. SZCZ?SNY",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "POLAND",
     "Height": 196,
     "Weight": 85,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CMF",
     "Player Name": "R. NAINGGOLAN",
     "Team Name": "INTERNAZIONALE",
     "Nationality": "BELGIUM",
     "Height": 176,
     "Weight": 65,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "GK",
     "Player Name": "B. LENO",
     "Team Name": "ARSENAL",
     "Nationality": "GERMANY",
     "Height": 190,
     "Weight": 83,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "RWF",
     "Player Name": "R. STERLING",
     "Team Name": "MAN BLUE",
     "Nationality": "ENGLAND",
     "Height": 170,
     "Weight": 69,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CB",
     "Player Name": "MARQUINHOS",
     "Team Name": "PSG",
     "Nationality": "BRAZIL",
     "Height": 183,
     "Weight": 75,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "RMF",
     "Player Name": "F. THAUVIN",
     "Team Name": "OLYMPIQUE MARSEILLE",
     "Nationality": "FRANCE",
     "Height": 179,
     "Weight": 70,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CB",
     "Player Name": "K. KOULIBALY",
     "Team Name": "NAPOLI",
     "Nationality": "SENEGAL",
     "Height": 187,
     "Weight": 89,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "LWF",
     "Player Name": "L. SAN�",
     "Team Name": "MAN BLUE",
     "Nationality": "GERMANY",
     "Height": 183,
     "Weight": 75,
     "Age": 22,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CF",
     "Player Name": "GABRIEL JESUS",
     "Team Name": "MAN BLUE",
     "Nationality": "BRAZIL",
     "Height": 175,
     "Weight": 73,
     "Age": 21,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CMF",
     "Player Name": "S. M. SAVI?",
     "Team Name": "LAZIO",
     "Nationality": "SERBIA",
     "Height": 192,
     "Weight": 82,
     "Age": 23,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CF",
     "Player Name": "T. WERNER",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 180,
     "Weight": 75,
     "Age": 22,
     "Condition": "C",
     "Overall Rating": 85
  },
  {
     "Position": "CB",
     "Player Name": "A. BARZAGLI",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "ITALY",
     "Height": 187,
     "Weight": 88,
     "Age": 37,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "PEPE",
     "Team Name": "BE??KTA?",
     "Nationality": "PORTUGAL",
     "Height": 188,
     "Weight": 81,
     "Age": 35,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CF",
     "Player Name": "R. FALCAO",
     "Team Name": "MONACO",
     "Nationality": "COLOMBIA",
     "Height": 177,
     "Weight": 72,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CMF",
     "Player Name": "B. MATUIDI",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "FRANCE",
     "Height": 175,
     "Weight": 70,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CMF",
     "Player Name": "M. DEMB�L�",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "BELGIUM",
     "Height": 185,
     "Weight": 82,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "NALDO",
     "Team Name": "SCHALKE 04",
     "Nationality": "BRAZIL",
     "Height": 198,
     "Weight": 91,
     "Age": 36,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "R. JARSTEIN",
     "Team Name": "Free Agents",
     "Nationality": "NORWAY",
     "Height": 190,
     "Weight": 82,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "AMF",
     "Player Name": "D. PAYET",
     "Team Name": "OLYMPIQUE MARSEILLE",
     "Nationality": "FRANCE",
     "Height": 175,
     "Weight": 77,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "RUI PATR�CIO",
     "Team Name": "WM GOLD",
     "Nationality": "PORTUGAL",
     "Height": 190,
     "Weight": 84,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "J. VERTONGHEN",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "BELGIUM",
     "Height": 189,
     "Weight": 86,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "S. RUFFIER",
     "Team Name": "SAINT-�TIENNE",
     "Nationality": "FRANCE",
     "Height": 188,
     "Weight": 93,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "F. FAZIO",
     "Team Name": "ROMA",
     "Nationality": "ARGENTINA",
     "Height": 195,
     "Weight": 85,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "SOKRATIS P.",
     "Team Name": "ARSENAL",
     "Nationality": "GREECE",
     "Height": 186,
     "Weight": 85,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CF",
     "Player Name": "M. BALOTELLI",
     "Team Name": "NICE",
     "Nationality": "ITALY",
     "Height": 189,
     "Weight": 88,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CMF",
     "Player Name": "A. RAMSEY",
     "Team Name": "ARSENAL",
     "Nationality": "WALES",
     "Height": 178,
     "Weight": 76,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "RWF",
     "Player Name": "JOS� CALLEJ�N",
     "Team Name": "NAPOLI",
     "Nationality": "SPAIN",
     "Height": 178,
     "Weight": 73,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "LMF",
     "Player Name": "I. PERI�I?",
     "Team Name": "INTERNAZIONALE",
     "Nationality": "CROATIA",
     "Height": 186,
     "Weight": 79,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CF",
     "Player Name": "O. GIROUD",
     "Team Name": "LONDON FC",
     "Nationality": "FRANCE",
     "Height": 192,
     "Weight": 88,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CMF",
     "Player Name": "DANI PAREJO",
     "Team Name": "ED WHITE ORANGE",
     "Nationality": "SPAIN",
     "Height": 180,
     "Weight": 73,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "L. KOSCIELNY",
     "Team Name": "ARSENAL",
     "Nationality": "FRANCE",
     "Height": 186,
     "Weight": 75,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "M. PERIN",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "ITALY",
     "Height": 188,
     "Weight": 77,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "RMF",
     "Player Name": "JUAN CUADRADO",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "COLOMBIA",
     "Height": 179,
     "Weight": 71,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "S. DE VRIJ",
     "Team Name": "INTERNAZIONALE",
     "Nationality": "NETHERLANDS",
     "Height": 188,
     "Weight": 78,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "ANTHONY LOPES",
     "Team Name": "OLYMPIQUE LYONNAIS",
     "Nationality": "PORTUGAL",
     "Height": 184,
     "Weight": 81,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "RB",
     "Player Name": "K. WALKER",
     "Team Name": "MAN BLUE",
     "Nationality": "ENGLAND",
     "Height": 178,
     "Weight": 70,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "LMF",
     "Player Name": "SON HEUNG-MIN",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "REPUBLIC OF KOREA",
     "Height": 183,
     "Weight": 79,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CMF",
     "Player Name": "G. KONDOGBIA",
     "Team Name": "ED WHITE ORANGE",
     "Nationality": "FRANCE",
     "Height": 188,
     "Weight": 76,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CF",
     "Player Name": "�LVARO MORATA",
     "Team Name": "LONDON FC",
     "Nationality": "SPAIN",
     "Height": 189,
     "Weight": 85,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "DMF",
     "Player Name": "LUIZ GUSTAVO",
     "Team Name": "OLYMPIQUE MARSEILLE",
     "Nationality": "BRAZIL",
     "Height": 187,
     "Weight": 78,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "NETO",
     "Team Name": "ED WHITE ORANGE",
     "Nationality": "BRAZIL",
     "Height": 192,
     "Weight": 84,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CF",
     "Player Name": "M. BATSHUAYI",
     "Team Name": "ED WHITE ORANGE",
     "Nationality": "BELGIUM",
     "Height": 184,
     "Weight": 88,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CMF",
     "Player Name": "?. G�NDO?AN",
     "Team Name": "MAN BLUE",
     "Nationality": "GERMANY",
     "Height": 180,
     "Weight": 80,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "LWF",
     "Player Name": "J. DRAXLER",
     "Team Name": "PSG",
     "Nationality": "GERMANY",
     "Height": 187,
     "Weight": 76,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "R. F�HRMANN",
     "Team Name": "SCHALKE 04",
     "Nationality": "GERMANY",
     "Height": 196,
     "Weight": 95,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "AMF",
     "Player Name": "H. ZIYECH",
     "Team Name": "AJAX",
     "Nationality": "MOROCCO",
     "Height": 183,
     "Weight": 68,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "J. PICKFORD",
     "Team Name": "MERSEYSIDE BLUE",
     "Nationality": "ENGLAND",
     "Height": 185,
     "Weight": 77,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "RB",
     "Player Name": "DANIEL CARVAJAL",
     "Team Name": "MD WHITE",
     "Nationality": "SPAIN",
     "Height": 173,
     "Weight": 73,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "J. GIM�NEZ",
     "Team Name": "KB RED WHITE",
     "Nationality": "URUGUAY",
     "Height": 185,
     "Weight": 80,
     "Age": 23,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CMF",
     "Player Name": "L. GORETZKA",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 189,
     "Weight": 79,
     "Age": 23,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "RMF",
     "Player Name": "R. MAHREZ",
     "Team Name": "MAN BLUE",
     "Nationality": "ALGERIA",
     "Height": 179,
     "Weight": 67,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "DMF",
     "Player Name": "FABINHO",
     "Team Name": "LIVERPOOL",
     "Nationality": "BRAZIL",
     "Height": 188,
     "Weight": 78,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "DMF",
     "Player Name": "T. PARTEY",
     "Team Name": "KB RED WHITE",
     "Nationality": "GHANA",
     "Height": 185,
     "Weight": 78,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "LMF",
     "Player Name": "MARCO ASENSIO",
     "Team Name": "MD WHITE",
     "Nationality": "SPAIN",
     "Height": 180,
     "Weight": 75,
     "Age": 22,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "RWF",
     "Player Name": "BERNARDO SILVA",
     "Team Name": "MAN BLUE",
     "Nationality": "PORTUGAL",
     "Height": 173,
     "Weight": 64,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "AMF",
     "Player Name": "D. ALLI",
     "Team Name": "NORTH EAST LONDON",
     "Nationality": "ENGLAND",
     "Height": 188,
     "Weight": 76,
     "Age": 22,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "LWF",
     "Player Name": "L. BAILEY",
     "Team Name": "BAYER LEVERKUSEN",
     "Nationality": "JAMAICA",
     "Height": 180,
     "Weight": 75,
     "Age": 21,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "CB",
     "Player Name": "N. S�LE",
     "Team Name": "Free Agents",
     "Nationality": "GERMANY",
     "Height": 195,
     "Weight": 97,
     "Age": 23,
     "Condition": "C",
     "Overall Rating": 84
  },
  {
     "Position": "GK",
     "Player Name": "P. ?ECH",
     "Team Name": "ARSENAL",
     "Nationality": "CZECH REPUBLIC",
     "Height": 196,
     "Weight": 90,
     "Age": 36,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "DMF",
     "Player Name": "D. DE ROSSI",
     "Team Name": "ROMA",
     "Nationality": "ITALY",
     "Height": 184,
     "Weight": 83,
     "Age": 35,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CB",
     "Player Name": "ALBIOL",
     "Team Name": "NAPOLI",
     "Nationality": "SPAIN",
     "Height": 190,
     "Weight": 82,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "RB",
     "Player Name": "DANI ALVES",
     "Team Name": "PSG",
     "Nationality": "BRAZIL",
     "Height": 172,
     "Weight": 68,
     "Age": 35,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "RB",
     "Player Name": "A. VALENCIA",
     "Team Name": "MAN RED",
     "Nationality": "ECUADOR",
     "Height": 180,
     "Weight": 83,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "SS",
     "Player Name": "JONAS",
     "Team Name": "BENFICA",
     "Nationality": "BRAZIL",
     "Height": 181,
     "Weight": 74,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "DMF",
     "Player Name": "L. BIGLIA",
     "Team Name": "MILAN",
     "Nationality": "ARGENTINA",
     "Height": 178,
     "Weight": 63,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CF",
     "Player Name": "M. ARNAUTOVI?",
     "Team Name": "EAST LONDON",
     "Nationality": "AUSTRIA",
     "Height": 192,
     "Weight": 83,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CMF",
     "Player Name": "C. MARCHISIO",
     "Team Name": "ZENIT",
     "Nationality": "ITALY",
     "Height": 180,
     "Weight": 75,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "AMF",
     "Player Name": "�. BANEGA",
     "Team Name": "AN WHITE RED",
     "Nationality": "ARGENTINA",
     "Height": 173,
     "Weight": 73,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "GK",
     "Player Name": "Y. SOMMER",
     "Team Name": "Free Agents",
     "Nationality": "SWITZERLAND",
     "Height": 183,
     "Weight": 79,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CF",
     "Player Name": "M. MAND�UKI?",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "CROATIA",
     "Height": 190,
     "Weight": 86,
     "Age": 32,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "GK",
     "Player Name": "S. MANDANDA",
     "Team Name": "OLYMPIQUE MARSEILLE",
     "Nationality": "FRANCE",
     "Height": 185,
     "Weight": 82,
     "Age": 33,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CMF",
     "Player Name": "G. BONAVENTURA",
     "Team Name": "MILAN",
     "Nationality": "ITALY",
     "Height": 180,
     "Weight": 75,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CMF",
     "Player Name": "K. STROOTMAN",
     "Team Name": "OLYMPIQUE MARSEILLE",
     "Nationality": "NETHERLANDS",
     "Height": 186,
     "Weight": 78,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "GK",
     "Player Name": "D. SUBA�I?",
     "Team Name": "MONACO",
     "Nationality": "CROATIA",
     "Height": 191,
     "Weight": 84,
     "Age": 34,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "AMF",
     "Player Name": "J. PASTORE",
     "Team Name": "ROMA",
     "Nationality": "ARGENTINA",
     "Height": 187,
     "Weight": 78,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "DMF",
     "Player Name": "S. NZONZI",
     "Team Name": "ROMA",
     "Nationality": "FRANCE",
     "Height": 196,
     "Weight": 75,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CMF",
     "Player Name": "S. KHEDIRA",
     "Team Name": "PM BLACK WHITE",
     "Nationality": "GERMANY",
     "Height": 189,
     "Weight": 93,
     "Age": 31,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CB",
     "Player Name": "B. H�WEDES",
     "Team Name": "LOKOMOTIV MOSKVA",
     "Nationality": "GERMANY",
     "Height": 187,
     "Weight": 82,
     "Age": 30,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "DMF",
     "Player Name": "G. XHAKA",
     "Team Name": "ARSENAL",
     "Nationality": "SWITZERLAND",
     "Height": 185,
     "Weight": 82,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CF",
     "Player Name": "RODRIGO",
     "Team Name": "ED WHITE ORANGE",
     "Nationality": "SPAIN",
     "Height": 182,
     "Weight": 70,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "GK",
     "Player Name": "A. AREOLA",
     "Team Name": "PSG",
     "Nationality": "FRANCE",
     "Height": 195,
     "Weight": 94,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "LB",
     "Player Name": "F. GHOULAM",
     "Team Name": "NAPOLI",
     "Nationality": "ALGERIA",
     "Height": 188,
     "Weight": 80,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "LMF",
     "Player Name": "MARCOS ALONSO",
     "Team Name": "LONDON FC",
     "Nationality": "SPAIN",
     "Height": 188,
     "Weight": 84,
     "Age": 28,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CB",
     "Player Name": "S. SAVI?",
     "Team Name": "KB RED WHITE",
     "Nationality": "MONTENEGRO",
     "Height": 186,
     "Weight": 73,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "AMF",
     "Player Name": "G. SIGUR�SSON",
     "Team Name": "MERSEYSIDE BLUE",
     "Nationality": "ICELAND",
     "Height": 186,
     "Weight": 79,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "RWF",
     "Player Name": "SUSO",
     "Team Name": "MILAN",
     "Nationality": "SPAIN",
     "Height": 176,
     "Weight": 70,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "LWF",
     "Player Name": "M. DEPAY",
     "Team Name": "OLYMPIQUE LYONNAIS",
     "Nationality": "NETHERLANDS",
     "Height": 176,
     "Weight": 78,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CMF",
     "Player Name": "A. RABIOT",
     "Team Name": "PSG",
     "Nationality": "FRANCE",
     "Height": 189,
     "Weight": 71,
     "Age": 23,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CB",
     "Player Name": "A. LAPORTE",
     "Team Name": "MAN BLUE",
     "Nationality": "FRANCE",
     "Height": 191,
     "Weight": 86,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CB",
     "Player Name": "J. STONES",
     "Team Name": "MAN BLUE",
     "Nationality": "ENGLAND",
     "Height": 188,
     "Weight": 70,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "LMF",
     "Player Name": "Y. CARRASCO",
     "Team Name": "Free Agents",
     "Nationality": "BELGIUM",
     "Height": 180,
     "Weight": 71,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CMF",
     "Player Name": "FRED",
     "Team Name": "MAN RED",
     "Nationality": "BRAZIL",
     "Height": 169,
     "Weight": 62,
     "Age": 25,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "DMF",
     "Player Name": "JORGINHO",
     "Team Name": "LONDON FC",
     "Nationality": "ITALY",
     "Height": 180,
     "Weight": 65,
     "Age": 27,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "RWF",
     "Player Name": "VITOLO",
     "Team Name": "KB RED WHITE",
     "Nationality": "SPAIN",
     "Height": 184,
     "Weight": 80,
     "Age": 29,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CF",
     "Player Name": "W. ZAHA",
     "Team Name": "SOUTH NORWOOD",
     "Nationality": "C�TE D'IVOIRE",
     "Height": 180,
     "Weight": 66,
     "Age": 26,
     "Condition": "C",
     "Overall Rating": 83
  },
  {
     "Position": "CMF",
     "Player Name": "C. TOLISSO",
     "Team Name": "Free Agents",
     "Nationality": "FRANCE",
     "Height": 181,
     "Weight": 78,
     "Age": 24,
     "Condition": "C",
     "Overall Rating": 83
  }
]